apiVersion: v1
kind: Service
metadata:
  name: notion-api-service
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttle: "4"
  labels:
    app: notion-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: notion-api
  sessionAffinity: None